---
name: workfront-usernote-builder

#also note component.api.key.<component-name>=a77ask
component:
  api:
    baseUrl: http://localhost:8080
    name: attask-usernote-builder
    key: a77ask

attask:
  consumer:
    name: RBQ
    pollInterval: 1000
    queueName: UserNoteBuilderEventQueue
    queueSize: 10
    requestChannel: rbqRequestChannel
    sourceChannel: userNoteSourceChannel
    topicPattern: Consumer.%s.VirtualTopic.%s
  ehcache:
    configfile: classpath:ehcache.xml
  cache:
    adminSession: adminSessionCache
    aspSession: aspSessionCache
    userSession: userSessionCache
    core:
      jmsBrokerURL: ${jms.broker.url}
      isReplicationEnabled: true
      activemq:
        active: true

spring:
  profiles:
    active: development,production,connection #not prototype, cachingConnection
  application:
    name: ${name}

# these are fallback properties for maven resolved ones
project:
  name: ${name}
  description: User Notification Builder Service
  version: 0.0.1
info:
  build:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

server.port: 9000

# this service info should be permissive
endpoints:
  health.sensitive: false
  shutdown.enabled: true
#  autoconfig.enabled: false
#  beans.enabled: false
#  configprops.enabled: false
#  dump.enabled: false
#  env.enabled: false
#  info.enabled: true
#  metrics.enabled: true
#  mappings.enabled: false
#  trace.enabled: false
  jmx:
    domain: com.workfront #defaults to org.springboot
    enabled: true
    uniqueNames: true

# need to fix this, want to register by status enum instead
#management.health.status.order: DOWN, OUT_OF_SERVICE, DEGRADED, UNKNOWN, UP

logging.level.org.springframework: DEBUG
